import collections

FunctionInfo = collections.namedtuple(
    'FunctionInfo', 'name category version')

function_info = (
    FunctionInfo('ABS', 'Math and trigonometry', ''),
    FunctionInfo('ACCRINT', 'Financial', ''),
    FunctionInfo('ACCRINTM', 'Financial', ''),
    FunctionInfo('ACOS', 'Math and trigonometry', ''),
    FunctionInfo('ACOSH', 'Math and trigonometry', ''),
    FunctionInfo('ACOT', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('ACOTH', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('AGGREGATE', 'Math and trigonometry', ''),
    FunctionInfo('ADDRESS', 'Lookup and reference', ''),
    FunctionInfo('AMORDEGRC', 'Financial', ''),
    FunctionInfo('AMORLINC', 'Financial', ''),
    FunctionInfo('AND', 'Logical', ''),
    FunctionInfo('ARABIC', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('AREAS', 'Lookup and reference', ''),
    FunctionInfo('ASC', 'Text', ''),
    FunctionInfo('ASIN', 'Math and trigonometry', ''),
    FunctionInfo('ASINH', 'Math and trigonometry', ''),
    FunctionInfo('ATAN', 'Math and trigonometry', ''),
    FunctionInfo('ATAN2', 'Math and trigonometry', ''),
    FunctionInfo('ATANH', 'Math and trigonometry', ''),
    FunctionInfo('AVEDEV', 'Statistical', ''),
    FunctionInfo('AVERAGE', 'Statistical', ''),
    FunctionInfo('AVERAGEA', 'Statistical', ''),
    FunctionInfo('AVERAGEIF', 'Statistical', ''),
    FunctionInfo('AVERAGEIFS', 'Statistical', ''),
    FunctionInfo('BAHTTEXT', 'Text', ''),
    FunctionInfo('BASE', 'Math and trigonometry', ''),
    FunctionInfo('BESSELI', 'Engineering', ''),
    FunctionInfo('BESSELJ', 'Engineering', ''),
    FunctionInfo('BESSELK', 'Engineering', ''),
    FunctionInfo('BESSELY', 'Engineering', ''),
    FunctionInfo('BETADIST', 'Compatibility', ''),
    FunctionInfo('BETA.DIST', 'Statistical', 'Excel 2010'),
    FunctionInfo('BETAINV', 'Compatibility', ''),
    FunctionInfo('BETA.INV', 'Statistical', 'Excel 2010'),
    FunctionInfo('BIN2DEC', 'Engineering', ''),
    FunctionInfo('BIN2HEX', 'Engineering', ''),
    FunctionInfo('BIN2OCT', 'Engineering', ''),
    FunctionInfo('BINOMDIST', 'Compatibility', ''),
    FunctionInfo('BINOM.DIST', 'Statistical', 'Excel 2010'),
    FunctionInfo('BINOM.DIST.RANGE', 'Statistical', 'Excel 2013'),
    FunctionInfo('BINOM.INV', 'Statistical', 'Excel 2010'),
    FunctionInfo('BITAND', 'Engineering', 'Excel 2013'),
    FunctionInfo('BITLSHIFT', 'Engineering', 'Excel 2013'),
    FunctionInfo('BITOR', 'Engineering', 'Excel 2013'),
    FunctionInfo('BITRSHIFT', 'Engineering', 'Excel 2013'),
    FunctionInfo('BITXOR', 'Engineering', 'Excel 2013'),
    FunctionInfo('CALL', 'Add-in and Automation', ''),
    FunctionInfo('CEILING', 'Math and trigonometry', ''),
    FunctionInfo('CEILING.MATH', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('CEILING.PRECISE', 'Math and trigonometry', ''),
    FunctionInfo('CELL', 'Information', ''),
    FunctionInfo('CHAR', 'Text', ''),
    FunctionInfo('CHIDIST', 'Compatibility', ''),
    FunctionInfo('CHIINV', 'Compatibility', ''),
    FunctionInfo('CHITEST', 'Compatibility', ''),
    FunctionInfo('CHISQ.DIST', 'Statistical', 'Excel 2010'),
    FunctionInfo('CHISQ.DIST.RT', 'Statistical', 'Excel 2010'),
    FunctionInfo('CHISQ.INV', 'Statistical', 'Excel 2010'),
    FunctionInfo('CHISQ.INV.RT', 'Statistical', 'Excel 2010'),
    FunctionInfo('CHISQ.TEST', 'Statistical', 'Excel 2010'),
    FunctionInfo('CHOOSE', 'Lookup and reference', ''),
    FunctionInfo('CLEAN', 'Text', ''),
    FunctionInfo('CODE', 'Text', ''),
    FunctionInfo('COLUMN', 'Lookup and reference', ''),
    FunctionInfo('COLUMNS', 'Lookup and reference', ''),
    FunctionInfo('COMBIN', 'Math and trigonometry', ''),
    FunctionInfo('COMBINA', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('COMPLEX', 'Engineering', ''),
    FunctionInfo('CONCAT', 'Text', 'Excel 2016'),
    FunctionInfo('CONCATENATE', 'Text', ''),
    FunctionInfo('CONFIDENCE', 'Compatibility', ''),
    FunctionInfo('CONFIDENCE.NORM', 'Statistical', 'Excel 2010'),
    FunctionInfo('CONFIDENCE.T', 'Statistical', 'Excel 2010'),
    FunctionInfo('CONVERT', 'Engineering', ''),
    FunctionInfo('CORREL', 'Statistical', ''),
    FunctionInfo('COS', 'Math and trigonometry', ''),
    FunctionInfo('COSH', 'Math and trigonometry', ''),
    FunctionInfo('COT', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('COTH', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('COUNT', 'Statistical', ''),
    FunctionInfo('COUNTA', 'Statistical', ''),
    FunctionInfo('COUNTBLANK', 'Statistical', ''),
    FunctionInfo('COUNTIF', 'Statistical', ''),
    FunctionInfo('COUNTIFS', 'Statistical', ''),
    FunctionInfo('COUPDAYBS', 'Financial', ''),
    FunctionInfo('COUPDAYS', 'Financial', ''),
    FunctionInfo('COUPDAYSNC', 'Financial', ''),
    FunctionInfo('COUPNCD', 'Financial', ''),
    FunctionInfo('COUPNUM', 'Financial', ''),
    FunctionInfo('COUPPCD', 'Financial', ''),
    FunctionInfo('COVAR', 'Compatibility', ''),
    FunctionInfo('COVARIANCE.P', 'Statistical', 'Excel 2010'),
    FunctionInfo('COVARIANCE.S', 'Statistical', 'Excel 2010'),
    FunctionInfo('CRITBINOM', 'Compatibility', ''),
    FunctionInfo('CSC', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('CSCH', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('CUBEKPIMEMBER', 'Cube', ''),
    FunctionInfo('CUBEMEMBER', 'Cube', ''),
    FunctionInfo('CUBEMEMBERPROPERTY', 'Cube', ''),
    FunctionInfo('CUBERANKEDMEMBER', 'Cube', ''),
    FunctionInfo('CUBESET', 'Cube', ''),
    FunctionInfo('CUBESETCOUNT', 'Cube', ''),
    FunctionInfo('CUBEVALUE', 'Cube', ''),
    FunctionInfo('CUMIPMT', 'Financial', ''),
    FunctionInfo('CUMPRINC', 'Financial', ''),
    FunctionInfo('DATE', 'Date and time', ''),
    FunctionInfo('DATEDIF', 'Date and time', ''),
    FunctionInfo('DATEVALUE', 'Date and time', ''),
    FunctionInfo('DAVERAGE', 'Database', ''),
    FunctionInfo('DAY', 'Date and time', ''),
    FunctionInfo('DAYS', 'Date and time', 'Excel 2013'),
    FunctionInfo('DAYS360', 'Date and time', ''),
    FunctionInfo('DB', 'Financial', ''),
    FunctionInfo('DBCS', 'Text', 'Excel 2013'),
    FunctionInfo('DCOUNT', 'Database', ''),
    FunctionInfo('DCOUNTA', 'Database', ''),
    FunctionInfo('DDB', 'Financial', ''),
    FunctionInfo('DEC2BIN', 'Engineering', ''),
    FunctionInfo('DEC2HEX', 'Engineering', ''),
    FunctionInfo('DEC2OCT', 'Engineering', ''),
    FunctionInfo('DECIMAL', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('DEGREES', 'Math and trigonometry', ''),
    FunctionInfo('DELTA', 'Engineering', ''),
    FunctionInfo('DEVSQ', 'Statistical', ''),
    FunctionInfo('DGET', 'Database', ''),
    FunctionInfo('DISC', 'Financial', ''),
    FunctionInfo('DMAX', 'Database', ''),
    FunctionInfo('DMIN', 'Database', ''),
    FunctionInfo('DOLLAR', 'Text', ''),
    FunctionInfo('DOLLARDE', 'Financial', ''),
    FunctionInfo('DOLLARFR', 'Financial', ''),
    FunctionInfo('DPRODUCT', 'Database', ''),
    FunctionInfo('DSTDEV', 'Database', ''),
    FunctionInfo('DSTDEVP', 'Database', ''),
    FunctionInfo('DSUM', 'Database', ''),
    FunctionInfo('DURATION', 'Financial', ''),
    FunctionInfo('DVAR', 'Database', ''),
    FunctionInfo('DVARP', 'Database', ''),
    FunctionInfo('EDATE', 'Date and time', ''),
    FunctionInfo('EFFECT', 'Financial', ''),
    FunctionInfo('ENCODEURL', 'Web', 'Excel 2013'),
    FunctionInfo('EOMONTH', 'Date and time', 'Excel 2010'),
    FunctionInfo('ERF', 'Engineering', ''),
    FunctionInfo('ERF.PRECISE', 'Engineering', 'Excel 2010'),
    FunctionInfo('ERFC', 'Engineering', ''),
    FunctionInfo('ERFC.PRECISE', 'Engineering', 'Excel 2010'),
    FunctionInfo('ERROR.TYPE', 'Information', ''),
    FunctionInfo('EUROCONVERT', 'Add-in and Automation', ''),
    FunctionInfo('EVEN', 'Math and trigonometry', ''),
    FunctionInfo('EXACT', 'Text', ''),
    FunctionInfo('EXP', 'Math and trigonometry', ''),
    FunctionInfo('EXPON.DIST', 'Statistical', 'Excel 2010'),
    FunctionInfo('EXPONDIST', 'Compatibility', ''),
    FunctionInfo('FACT', 'Math and trigonometry', ''),
    FunctionInfo('FACTDOUBLE', 'Math and trigonometry', ''),
    FunctionInfo('FALSE', 'Logical', ''),
    FunctionInfo('F.DIST', 'Statistical', 'Excel 2010'),
    FunctionInfo('FDIST', 'Compatibility', ''),
    FunctionInfo('F.DIST.RT', 'Statistical', 'Excel 2010'),
    FunctionInfo('FILTER', 'Lookup and reference', 'Office 365'),
    FunctionInfo('FILTERXML', 'Web', 'Excel 2013'),
    FunctionInfo('FIND,  FINDBs', 'Text', ''),
    FunctionInfo('F.INV', 'Statistical', 'Excel 2010'),
    FunctionInfo('F.INV.RT', 'Statistical', 'Excel 2010'),
    FunctionInfo('FINV', 'Statistical', ''),
    FunctionInfo('FISHER', 'Statistical', ''),
    FunctionInfo('FISHERINV', 'Statistical', ''),
    FunctionInfo('FIXED', 'Text', ''),
    FunctionInfo('FLOOR', 'Compatibility', ''),
    FunctionInfo('FLOOR.MATH', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('FLOOR.PRECISE', 'Math and trigonometry', ''),
    FunctionInfo('FORECAST', 'Statistical', ''),
    FunctionInfo('FORECAST.ETS', 'Statistical', 'Excel 2016'),
    FunctionInfo('FORECAST.ETS.CONFINT', 'Statistical', 'Excel 2016'),
    FunctionInfo('FORECAST.ETS.SEASONALITY', 'Statistical', 'Excel 2016'),
    FunctionInfo('FORECAST.ETS.STAT', 'Statistical', 'Excel 2016'),
    FunctionInfo('FORECAST.LINEAR', 'Statistical', 'Excel 2016'),
    FunctionInfo('FORMULATEXT', 'Lookup and reference', 'Excel 2013'),
    FunctionInfo('FREQUENCY', 'Statistical', ''),
    FunctionInfo('F.TEST', 'Statistical', 'Excel 2010'),
    FunctionInfo('FTEST', 'Compatibility', ''),
    FunctionInfo('FV', 'Financial', ''),
    FunctionInfo('FVSCHEDULE', 'Financial', ''),
    FunctionInfo('GAMMA', 'Statistical', 'Excel 2013'),
    FunctionInfo('GAMMA.DIST', 'Statistical', 'Excel 2010'),
    FunctionInfo('GAMMADIST', 'Compatibility', ''),
    FunctionInfo('GAMMA.INV', 'Statistical', 'Excel 2010'),
    FunctionInfo('GAMMAINV', 'Compatibility', ''),
    FunctionInfo('GAMMALN', 'Statistical', ''),
    FunctionInfo('GAMMALN.PRECISE', 'Statistical', 'Excel 2010'),
    FunctionInfo('GAUSS', 'Statistical', 'Excel 2013'),
    FunctionInfo('GCD', 'Math and trigonometry', ''),
    FunctionInfo('GEOMEAN', 'Statistical', ''),
    FunctionInfo('GESTEP', 'Engineering', ''),
    FunctionInfo('GETPIVOTDATA', 'Lookup and reference', ''),
    FunctionInfo('GROWTH', 'Statistical', ''),
    FunctionInfo('HARMEAN', 'Statistical', ''),
    FunctionInfo('HEX2BIN', 'Engineering', ''),
    FunctionInfo('HEX2DEC', 'Engineering', ''),
    FunctionInfo('HEX2OCT', 'Engineering', ''),
    FunctionInfo('HLOOKUP', 'Lookup and reference', ''),
    FunctionInfo('HOUR', 'Date and time', ''),
    FunctionInfo('HYPERLINK', 'Lookup and reference', ''),
    FunctionInfo('HYPGEOM.DIST', 'Statistical', ''),
    FunctionInfo('HYPGEOMDIST', 'Compatibility', ''),
    FunctionInfo('IF', 'Logical', ''),
    FunctionInfo('IFERROR', 'Logical', ''),
    FunctionInfo('IFNA', 'Logical', 'Excel 2013'),
    FunctionInfo('IFS', 'Logical', 'Excel 2016'),
    FunctionInfo('IMABS', 'Engineering', ''),
    FunctionInfo('IMAGINARY', 'Engineering', ''),
    FunctionInfo('IMARGUMENT', 'Engineering', ''),
    FunctionInfo('IMCONJUGATE', 'Engineering', ''),
    FunctionInfo('IMCOS', 'Engineering', ''),
    FunctionInfo('IMCOSH', 'Engineering', 'Excel 2013'),
    FunctionInfo('IMCOT', 'Engineering', 'Excel 2013'),
    FunctionInfo('IMCSC', 'Engineering', 'Excel 2013'),
    FunctionInfo('IMCSCH', 'Engineering', 'Excel 2013'),
    FunctionInfo('IMDIV', 'Engineering', ''),
    FunctionInfo('IMEXP', 'Engineering', ''),
    FunctionInfo('IMLN', 'Engineering', ''),
    FunctionInfo('IMLOG10', 'Engineering', ''),
    FunctionInfo('IMLOG2', 'Engineering', ''),
    FunctionInfo('IMPOWER', 'Engineering', ''),
    FunctionInfo('IMPRODUCT', 'Engineering', ''),
    FunctionInfo('IMREAL', 'Engineering', ''),
    FunctionInfo('IMSEC', 'Engineering', 'Excel 2013'),
    FunctionInfo('IMSECH', 'Engineering', 'Excel 2013'),
    FunctionInfo('IMSIN', 'Engineering', ''),
    FunctionInfo('IMSINH', 'Engineering', 'Excel 2013'),
    FunctionInfo('IMSQRT', 'Engineering', ''),
    FunctionInfo('IMSUB', 'Engineering', ''),
    FunctionInfo('IMSUM', 'Engineering', ''),
    FunctionInfo('IMTAN', 'Engineering', 'Excel 2013'),
    FunctionInfo('INDEX', 'Lookup and reference', ''),
    FunctionInfo('INDIRECT', 'Lookup and reference', ''),
    FunctionInfo('INFO', 'Information', ''),
    FunctionInfo('INT', 'Math and trigonometry', ''),
    FunctionInfo('INTERCEPT', 'Statistical', ''),
    FunctionInfo('INTRATE', 'Financial', ''),
    FunctionInfo('IPMT', 'Financial', ''),
    FunctionInfo('IRR', 'Financial', ''),
    FunctionInfo('ISBLANK', 'Information', ''),
    FunctionInfo('ISERR', 'Information', ''),
    FunctionInfo('ISERROR', 'Information', ''),
    FunctionInfo('ISEVEN', 'Information', ''),
    FunctionInfo('ISFORMULA', 'Information', 'Excel 2013'),
    FunctionInfo('ISLOGICAL', 'Information', ''),
    FunctionInfo('ISNA', 'Information', ''),
    FunctionInfo('ISNONTEXT', 'Information', ''),
    FunctionInfo('ISNUMBER', 'Information', ''),
    FunctionInfo('ISODD', 'Information', ''),
    FunctionInfo('ISREF', 'Information', ''),
    FunctionInfo('ISTEXT', 'Information', ''),
    FunctionInfo('ISO.CEILING', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('ISOWEEKNUM', 'Date and time', 'Excel 2013'),
    FunctionInfo('ISPMT', 'Financial', ''),
    FunctionInfo('JIS', 'Text', ''),
    FunctionInfo('KURT', 'Statistical', ''),
    FunctionInfo('LARGE', 'Statistical', ''),
    FunctionInfo('LCM', 'Math and trigonometry', ''),
    FunctionInfo('LEFT,  LEFTBs', 'Text', ''),
    FunctionInfo('LEN,  LENBs', 'Text', ''),
    FunctionInfo('LINEST', 'Statistical', ''),
    FunctionInfo('LN', 'Math and trigonometry', ''),
    FunctionInfo('LOG', 'Math and trigonometry', ''),
    FunctionInfo('LOG10', 'Math and trigonometry', ''),
    FunctionInfo('LOGEST', 'Statistical', ''),
    FunctionInfo('LOGINV', 'Compatibility', ''),
    FunctionInfo('LOGNORM.DIST', 'Statistical', 'Excel 2010'),
    FunctionInfo('LOGNORMDIST', 'Compatibility', ''),
    FunctionInfo('LOGNORM.INV', 'Statistical', 'Excel 2010'),
    FunctionInfo('LOOKUP', 'Lookup and reference', ''),
    FunctionInfo('LOWER', 'Text', ''),
    FunctionInfo('MATCH', 'Lookup and reference', ''),
    FunctionInfo('MAX', 'Statistical', ''),
    FunctionInfo('MAXA', 'Statistical', ''),
    FunctionInfo('MAXIFS', 'Statistical', 'Excel 2016'),
    FunctionInfo('MDETERM', 'Math and trigonometry', ''),
    FunctionInfo('MDURATION', 'Financial', ''),
    FunctionInfo('MEDIAN', 'Statistical', ''),
    FunctionInfo('MID,  MIDBs', 'Text', ''),
    FunctionInfo('MIN', 'Statistical', ''),
    FunctionInfo('MINIFS', 'Statistical', 'Excel 2016'),
    FunctionInfo('MINA', 'Statistical', ''),
    FunctionInfo('MINUTE', 'Date and time', ''),
    FunctionInfo('MINVERSE', 'Math and trigonometry', ''),
    FunctionInfo('MIRR', 'Financial', ''),
    FunctionInfo('MMULT', 'Math and trigonometry', ''),
    FunctionInfo('MOD', 'Math and trigonometry', ''),
    FunctionInfo('MODE', 'Compatibility', ''),
    FunctionInfo('MODE.MULT', 'Statistical', 'Excel 2010'),
    FunctionInfo('MODE.SNGL', 'Statistical', 'Excel 2010'),
    FunctionInfo('MONTH', 'Date and time', ''),
    FunctionInfo('MROUND', 'Math and trigonometry', ''),
    FunctionInfo('MULTINOMIAL', 'Math and trigonometry', ''),
    FunctionInfo('MUNIT', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('N', 'Information', ''),
    FunctionInfo('NA', 'Information', ''),
    FunctionInfo('NEGBINOM.DIST', 'Statistical', 'Excel 2010'),
    FunctionInfo('NEGBINOMDIST', 'Compatibility', ''),
    FunctionInfo('NETWORKDAYS', 'Date and time', ''),
    FunctionInfo('NETWORKDAYS.INTL', 'Date and time', 'Excel 2010'),
    FunctionInfo('NOMINAL', 'Financial', ''),
    FunctionInfo('NORM.DIST', 'Statistical', 'Excel 2010'),
    FunctionInfo('NORMDIST', 'Compatibility', ''),
    FunctionInfo('NORMINV', 'Statistical', ''),
    FunctionInfo('NORM.INV', 'Compatibility', 'Excel 2010'),
    FunctionInfo('NORM.S.DIST', 'Statistical', 'Excel 2010'),
    FunctionInfo('NORMSDIST', 'Compatibility', ''),
    FunctionInfo('NORM.S.INV', 'Statistical', 'Excel 2010'),
    FunctionInfo('NORMSINV', 'Compatibility', ''),
    FunctionInfo('NOT', 'Logical', ''),
    FunctionInfo('NOW', 'Date and time', ''),
    FunctionInfo('NPER', 'Financial', ''),
    FunctionInfo('NPV', 'Financial', ''),
    FunctionInfo('NUMBERVALUE', 'Text', 'Excel 2013'),
    FunctionInfo('OCT2BIN', 'Engineering', ''),
    FunctionInfo('OCT2DEC', 'Engineering', ''),
    FunctionInfo('OCT2HEX', 'Engineering', ''),
    FunctionInfo('ODD', 'Math and trigonometry', ''),
    FunctionInfo('ODDFPRICE', 'Financial', ''),
    FunctionInfo('ODDFYIELD', 'Financial', ''),
    FunctionInfo('ODDLPRICE', 'Financial', ''),
    FunctionInfo('ODDLYIELD', 'Financial', ''),
    FunctionInfo('OFFSET', 'Lookup and reference', ''),
    FunctionInfo('OR', 'Logical', ''),
    FunctionInfo('PDURATION', 'Financial', 'Excel 2013'),
    FunctionInfo('PEARSON', 'Statistical', ''),
    FunctionInfo('PERCENTILE.EXC', 'Statistical', 'Excel 2010'),
    FunctionInfo('PERCENTILE.INC', 'Statistical', 'Excel 2010'),
    FunctionInfo('PERCENTILE', 'Compatibility', ''),
    FunctionInfo('PERCENTRANK.EXC', 'Statistical', 'Excel 2010'),
    FunctionInfo('PERCENTRANK.INC', 'Statistical', 'Excel 2010'),
    FunctionInfo('PERCENTRANK', 'Compatibility', ''),
    FunctionInfo('PERMUT', 'Statistical', ''),
    FunctionInfo('PERMUTATIONA', 'Statistical', 'Excel 2013'),
    FunctionInfo('PHI', 'Statistical', 'Excel 2013'),
    FunctionInfo('PHONETIC', 'Text', ''),
    FunctionInfo('PI', 'Math and trigonometry', ''),
    FunctionInfo('PMT', 'Financial', ''),
    FunctionInfo('POISSON.DIST', 'Statistical', 'Excel 2010'),
    FunctionInfo('POISSON', 'Compatibility', ''),
    FunctionInfo('POWER', 'Math and trigonometry', ''),
    FunctionInfo('PPMT', 'Financial', ''),
    FunctionInfo('PRICE', 'Financial', ''),
    FunctionInfo('PRICEDISC', 'Financial', ''),
    FunctionInfo('PRICEMAT', 'Financial', ''),
    FunctionInfo('PROB', 'Statistical', ''),
    FunctionInfo('PRODUCT', 'Math and trigonometry', ''),
    FunctionInfo('PROPER', 'Text', ''),
    FunctionInfo('PV', 'Financial', ''),
    FunctionInfo('QUARTILE', 'Compatibility', ''),
    FunctionInfo('QUARTILE.EXC', 'Statistical', 'Excel 2010'),
    FunctionInfo('QUARTILE.INC', 'Statistical', 'Excel 2010'),
    FunctionInfo('QUOTIENT', 'Math and trigonometry', ''),
    FunctionInfo('RADIANS', 'Math and trigonometry', ''),
    FunctionInfo('RAND', 'Math and trigonometry', ''),
    FunctionInfo('RANDARRAY', 'Math and trigonometry', 'Office 365'),
    FunctionInfo('RANDBETWEEN', 'Math and trigonometry', ''),
    FunctionInfo('RANK.AVG', 'Statistical', 'Excel 2010'),
    FunctionInfo('RANK.EQ', 'Statistical', 'Excel 2010'),
    FunctionInfo('RANK', 'Compatibility', ''),
    FunctionInfo('RATE', 'Financial', ''),
    FunctionInfo('RECEIVED', 'Financial', ''),
    FunctionInfo('REGISTER.ID', 'Add-in and Automation', ''),
    FunctionInfo('REPLACE,  REPLACEBs', 'Text', ''),
    FunctionInfo('REPT', 'Text', ''),
    FunctionInfo('RIGHT,  RIGHTBs', 'Text', ''),
    FunctionInfo('ROMAN', 'Math and trigonometry', ''),
    FunctionInfo('ROUND', 'Math and trigonometry', ''),
    FunctionInfo('ROUNDDOWN', 'Math and trigonometry', ''),
    FunctionInfo('ROUNDUP', 'Math and trigonometry', ''),
    FunctionInfo('ROW', 'Lookup and reference', ''),
    FunctionInfo('ROWS', 'Lookup and reference', ''),
    FunctionInfo('RRI', 'Financial', 'Excel 2013'),
    FunctionInfo('RSQ', 'Statistical', ''),
    FunctionInfo('RTD', 'Lookup and reference', ''),
    FunctionInfo('SEARCH,  SEARCHBs', 'Text', ''),
    FunctionInfo('SEC', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('SECH', 'Math and trigonometry', 'Excel 2013'),
    FunctionInfo('SECOND', 'Date and time', ''),
    FunctionInfo('SEQUENCE', 'Math and trigonometry', 'Office 365'),
    FunctionInfo('SERIESSUM', 'Math and trigonometry', ''),
    FunctionInfo('SHEET', 'Information', 'Excel 2013'),
    FunctionInfo('SHEETS', 'Information', 'Excel 2013'),
    FunctionInfo('SIGN', 'Math and trigonometry', ''),
    FunctionInfo('SIN', 'Math and trigonometry', ''),
    FunctionInfo('SINGLE', 'Lookup and reference', ''),
    FunctionInfo('SINH', 'Math and trigonometry', ''),
    FunctionInfo('SKEW', 'Statistical', ''),
    FunctionInfo('SKEW.P', 'Statistical', 'Excel 2013'),
    FunctionInfo('SLN', 'Financial', ''),
    FunctionInfo('SLOPE', 'Statistical', ''),
    FunctionInfo('SMALL', 'Statistical', ''),
    FunctionInfo('SORT', 'Lookup and reference', 'Office 365'),
    FunctionInfo('SORTBY', 'Lookup and reference', 'Office 365'),
    FunctionInfo('SQRT', 'Math and trigonometry', ''),
    FunctionInfo('SQRTPI', 'Math and trigonometry', ''),
    FunctionInfo('STANDARDIZE', 'Statistical', ''),
    FunctionInfo('STDEV', 'Compatibility', ''),
    FunctionInfo('STDEV.P', 'Statistical', 'Excel 2010'),
    FunctionInfo('STDEV.S', 'Statistical', 'Excel 2010'),
    FunctionInfo('STDEVA', 'Statistical', ''),
    FunctionInfo('STDEVP', 'Compatibility', ''),
    FunctionInfo('STDEVPA', 'Statistical', ''),
    FunctionInfo('STEYX', 'Statistical', ''),
    FunctionInfo('SUBSTITUTE', 'Text', ''),
    FunctionInfo('SUBTOTAL', 'Math and trigonometry', ''),
    FunctionInfo('SUM', 'Math and trigonometry', ''),
    FunctionInfo('SUMIF', 'Math and trigonometry', ''),
    FunctionInfo('SUMIFS', 'Math and trigonometry', ''),
    FunctionInfo('SUMPRODUCT', 'Math and trigonometry', ''),
    FunctionInfo('SUMSQ', 'Math and trigonometry', ''),
    FunctionInfo('SUMX2MY2', 'Math and trigonometry', ''),
    FunctionInfo('SUMX2PY2', 'Math and trigonometry', ''),
    FunctionInfo('SUMXMY2', 'Math and trigonometry', ''),
    FunctionInfo('SWITCH', 'Logical', 'Excel 2016'),
    FunctionInfo('SYD', 'Financial', ''),
    FunctionInfo('T', 'Text', ''),
    FunctionInfo('TAN', 'Math and trigonometry', ''),
    FunctionInfo('TANH', 'Math and trigonometry', ''),
    FunctionInfo('TBILLEQ', 'Financial', ''),
    FunctionInfo('TBILLPRICE', 'Financial', ''),
    FunctionInfo('TBILLYIELD', 'Financial', ''),
    FunctionInfo('T.DIST', 'Statistical', 'Excel 2010'),
    FunctionInfo('T.DIST.2T', 'Statistical', 'Excel 2010'),
    FunctionInfo('T.DIST.RT', 'Statistical', 'Excel 2010'),
    FunctionInfo('TDIST', 'Compatibility', ''),
    FunctionInfo('TEXT', 'Text', ''),
    FunctionInfo('TEXTJOIN', 'Text', 'Excel 2016'),
    FunctionInfo('TIME', 'Date and time', ''),
    FunctionInfo('TIMEVALUE', 'Date and time', ''),
    FunctionInfo('T.INV', 'Statistical', 'Excel 2010'),
    FunctionInfo('T.INV.2T', 'Statistical', 'Excel 2010'),
    FunctionInfo('TINV', 'Compatibility', ''),
    FunctionInfo('TODAY', 'Date and time', ''),
    FunctionInfo('TRANSPOSE', 'Lookup and reference', ''),
    FunctionInfo('TREND', 'Statistical', ''),
    FunctionInfo('TRIM', 'Text', ''),
    FunctionInfo('TRIMMEAN', 'Statistical', ''),
    FunctionInfo('TRUE', 'Logical', ''),
    FunctionInfo('TRUNC', 'Math and trigonometry', ''),
    FunctionInfo('T.TEST', 'Statistical', 'Excel 2010'),
    FunctionInfo('TTEST', 'Compatibility', ''),
    FunctionInfo('TYPE', 'Information', ''),
    FunctionInfo('UNICHAR', 'Text', 'Excel 2013'),
    FunctionInfo('UNICODE', 'Text', 'Excel 2013'),
    FunctionInfo('UNIQUE', 'Lookup and reference', 'Office 365'),
    FunctionInfo('UPPER', 'Text', ''),
    FunctionInfo('VALUE', 'Text', ''),
    FunctionInfo('VAR', 'Compatibility', ''),
    FunctionInfo('VAR.P', 'Statistical', 'Excel 2010'),
    FunctionInfo('VAR.S', 'Statistical', 'Excel 2010'),
    FunctionInfo('VARA', 'Statistical', ''),
    FunctionInfo('VARP', 'Compatibility', ''),
    FunctionInfo('VARPA', 'Statistical', ''),
    FunctionInfo('VDB', 'Financial', ''),
    FunctionInfo('VLOOKUP', 'Lookup and reference', ''),
    FunctionInfo('WEBSERVICE', 'Web', 'Excel 2013'),
    FunctionInfo('WEEKDAY', 'Date and time', ''),
    FunctionInfo('WEEKNUM', 'Date and time', ''),
    FunctionInfo('WEIBULL', 'Compatibility', ''),
    FunctionInfo('WEIBULL.DIST', 'Statistical', 'Excel 2010'),
    FunctionInfo('WORKDAY', 'Date and time', ''),
    FunctionInfo('WORKDAY.INTL', 'Date and time', 'Excel 2010'),
    FunctionInfo('XIRR', 'Financial', ''),
    FunctionInfo('XNPV', 'Financial', ''),
    FunctionInfo('XOR', 'Logical', 'Excel 2013'),
    FunctionInfo('YEAR', 'Date and time', 'Excel 2007'),
    FunctionInfo('YEARFRAC', 'Date and time', ''),
    FunctionInfo('YIELD', 'Financial', ''),
    FunctionInfo('YIELDDISC', 'Financial', ''),
    FunctionInfo('YIELDMAT', 'Financial', ''),
    FunctionInfo('Z.TEST', 'Statistical', 'Excel 2010'),
    FunctionInfo('ZTEST', 'Compatibility', ''),
)
